-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";  -- For text search

-- Main projects table (Parent Board: 1825117125)
CREATE TABLE projects (
    -- Primary identifiers
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    monday_id TEXT UNIQUE NOT NULL,
    item_name TEXT NOT NULL,
    
    -- Core project fields
    project_name TEXT,
    pipeline_stage TEXT,
    status_category TEXT GENERATED ALWAYS AS (
        CASE
            WHEN pipeline_stage = 'Won - Closed (Invoiced)' THEN 'Won'
            WHEN pipeline_stage = 'Lost' THEN 'Lost'
            ELSE 'Open'
        END
    ) STORED,
    
    -- Categorical fields
    type TEXT,  -- New Build/Refurbishment
    category TEXT,  -- Apartments, Commercial, etc.
    zip_code TEXT,
    sales_representative TEXT,
    funding TEXT,
    
    -- Mirror resolved fields
    account TEXT,
    product_type TEXT,
    new_enquiry_value NUMERIC(12, 2) DEFAULT 0,
    
    -- Calculated fields
    gestation_period INTEGER CHECK (gestation_period >= 0 AND gestation_period <= 500000),
    project_value NUMERIC(12, 2),
    weighted_pipeline NUMERIC(12, 2),
    probability_percent INTEGER DEFAULT 0,
    
    -- Date fields
    date_created DATE,
    expected_start_date DATE,
    follow_up_date DATE,
    first_date_designed DATE,
    last_date_designed DATE,
    first_date_invoiced DATE,
    last_date_invoiced DATE,
    -- Always generated by Postgres from first_date_invoiced and last_date_invoiced.
    -- Do not INSERT or UPDATE this column from sync_service.py, backfill scripts, or API code.
    -- Rules:
    --   - NULL if either invoice date is missing.
    --   - 0 when first_date_invoiced = last_date_invoiced.
    --   - Otherwise, number of calendar days between first and last invoice dates.
    invoicing_spread_days INTEGER GENERATED ALWAYS AS (
        CASE
            WHEN first_date_invoiced IS NOT NULL
            AND last_date_invoiced IS NOT NULL
            THEN GREATEST(last_date_invoiced - first_date_invoiced, 0)
            ELSE NULL
        END
    ) STORED,

    -- Order fields
    total_order_value NUMERIC(12, 2),
    total_amount_invoiced NUMERIC(12, 2),
    date_order_received DATE,
    
    -- Feedback fields
    feedback TEXT,
    lost_to_who_or_why TEXT,
    
    -- Analysis fields
    value_band TEXT,  -- Computed during processing
    
    -- Metadata
    last_synced_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sync_version INTEGER DEFAULT 1
);

-- Subitems table (Subitem Board: 1825117144)
CREATE TABLE subitems (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    monday_id TEXT UNIQUE NOT NULL,
    parent_monday_id TEXT REFERENCES projects(monday_id) ON DELETE CASCADE,
    item_name TEXT,
    
    -- Connected board relations
    hidden_item_id TEXT REFERENCES hidden_items(monday_id) ON DELETE SET NULL,
    
    -- Mirror fields from hidden items
    account TEXT,
    product_type TEXT,
    new_enquiry_value NUMERIC(12, 2),
    reason_for_change TEXT,
    
    -- Design and quote fields
    date_received DATE,
    date_design_completed DATE,
    designer TEXT,
    time_taken NUMERIC(6, 2),
    surveyor TEXT,
    
    -- Area and specifications
    area NUMERIC(10, 2),
    fall TEXT,
    min_thickness NUMERIC(8, 2),
    max_thickness NUMERIC(8, 2),
    u_value NUMERIC(6, 4),
    deck_type TEXT,
    layering TEXT,
    
    -- Financial fields
    quote_amount NUMERIC(12, 2),
    m2_rate NUMERIC(10, 2),
    material_value NUMERIC(12, 2),
    transport_cost NUMERIC(10, 2),
    
    -- Order fields
    order_status TEXT,
    date_order_received DATE,
    cust_order_value_material NUMERIC(12, 2),
    customer_po TEXT,
    supplier1 TEXT,
    supplier2 TEXT,
    
    -- Delivery fields
    requested_delivery_date DATE,
    final_delivery_date DATE,
    delivery_address TEXT,
    
    -- Invoice fields
    invoice_number TEXT,
    invoice_date DATE,
    amount_invoiced NUMERIC(12, 2),
    
    -- Metadata
    last_synced_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Hidden items table (Hidden Items Board: 1825138260)
CREATE TABLE hidden_items (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    monday_id TEXT UNIQUE NOT NULL,
    item_name TEXT,
    status TEXT,
    project_attachments JSONB,
    prefix TEXT,
    revision TEXT,
    project_name TEXT,
    urgency TEXT,
    reason_for_change TEXT,
    approx_bonding TEXT,
    date_received DATE,
    date_design_completed DATE,
    date_quoted DATE,
    date_order_received DATE,
    cust_order_value_material NUMERIC(12, 2),
    date_project_won DATE,
    date_project_closed DATE,
    invoice_date DATE,
    invoice_number TEXT,
    amount_invoiced NUMERIC(12, 2),
    
    quote_amount NUMERIC(12, 2),
    material_value NUMERIC(12, 2),
    transport_cost NUMERIC(10, 2),
    target_gpm NUMERIC(6, 2),
    tp_margin NUMERIC(6, 2),
    commission NUMERIC(6, 2),
    distributor_margin NUMERIC(6, 2),
    time_taken NUMERIC(6, 2),
    min_thickness NUMERIC(8, 2),
    max_thickness NUMERIC(8, 2),
    volume_m3 NUMERIC(12, 3),
    wastage_percent NUMERIC(6, 2),
    account_id TEXT,
    contact_id TEXT,
    last_synced_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Sync tracking table
CREATE TABLE sync_log (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    sync_type TEXT NOT NULL CHECK (sync_type IN ('full', 'delta', 'webhook', 'reset')),
    board_id TEXT NOT NULL,
    board_name TEXT,
    started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    completed_at TIMESTAMP WITH TIME ZONE,
    status TEXT DEFAULT 'running' CHECK (status IN ('running', 'completed', 'failed')),
    items_processed INTEGER DEFAULT 0,
    items_created INTEGER DEFAULT 0,
    items_updated INTEGER DEFAULT 0,
    items_deleted INTEGER DEFAULT 0,
    error_message TEXT,
    metadata JSONB
);

-- Analysis results cache
CREATE TABLE analysis_results (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    project_id TEXT REFERENCES projects(monday_id) ON DELETE CASCADE,
    analysis_timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Predictions
    expected_gestation_days INTEGER,
    gestation_confidence NUMERIC(3, 2),
    expected_conversion_rate NUMERIC(3, 2),
    conversion_confidence NUMERIC(3, 2),
    rating_score INTEGER CHECK (rating_score >= 1 AND rating_score <= 100),
    
    -- Reasoning from LLM
    reasoning JSONB,
    adjustments JSONB,
    confidence_notes TEXT,
    special_factors TEXT,
    
    -- Metadata
    llm_model TEXT,
    analysis_version TEXT,
    processing_time_ms INTEGER
);

-- Create indexes separately
CREATE INDEX idx_analysis_project_id ON analysis_results (project_id);
CREATE INDEX idx_analysis_timestamp ON analysis_results (analysis_timestamp DESC);

-- Webhook events table for tracking
CREATE TABLE webhook_events (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    event_id TEXT UNIQUE,
    board_id TEXT,
    item_id TEXT,
    event_type TEXT,
    webhook_payload JSONB,
    received_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    processed_at TIMESTAMP WITH TIME ZONE,
    status TEXT DEFAULT 'pending',
    error_message TEXT,
    client_ip TEXT,
    processing_time_ms NUMERIC,
    retry_count INTEGER
);

-- Create all indexes separately
-- Projects table indexes
CREATE INDEX IF NOT EXISTS idx_projects_account ON projects (account);
CREATE INDEX IF NOT EXISTS idx_projects_type_category ON projects (type, category);
CREATE INDEX IF NOT EXISTS idx_projects_product_type ON projects (product_type);
CREATE INDEX IF NOT EXISTS idx_projects_status_category ON projects (status_category);
CREATE INDEX IF NOT EXISTS idx_projects_date_created ON projects (date_created);
CREATE INDEX IF NOT EXISTS idx_projects_monday_id ON projects (monday_id);
CREATE INDEX IF NOT EXISTS idx_projects_pipeline_stage ON projects (pipeline_stage);
CREATE INDEX IF NOT EXISTS idx_projects_total_order_value ON projects (total_order_value);
CREATE INDEX IF NOT EXISTS idx_projects_total_amount_invoiced ON projects (total_amount_invoiced);

CREATE INDEX IF NOT EXISTS idx_projects_first_date_invoiced
ON projects (first_date_invoiced)
WHERE first_date_invoiced IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_projects_last_date_invoiced
ON projects (last_date_invoiced)
WHERE last_date_invoiced IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_projects_invoice_date_range
ON projects (first_date_invoiced, last_date_invoiced)
WHERE first_date_invoiced IS NOT NULL
  AND last_date_invoiced IS NOT NULL;


-- Subitems table indexes
CREATE INDEX IF NOT EXISTS idx_subitems_parent ON subitems (parent_monday_id);
CREATE INDEX IF NOT EXISTS idx_subitems_hidden_item ON subitems (hidden_item_id);

-- Hidden items table indexes
CREATE INDEX IF NOT EXISTS idx_hidden_items_monday_id ON hidden_items (monday_id);
CREATE INDEX IF NOT EXISTS idx_hidden_items_date_received ON hidden_items (date_received);
CREATE INDEX IF NOT EXISTS idx_hidden_items_invoice_date ON hidden_items (invoice_date);
CREATE INDEX IF NOT EXISTS idx_hidden_items_invoice_number ON hidden_items (invoice_number);

-- Analysis results indexes
CREATE INDEX IF NOT EXISTS idx_analysis_project_id ON analysis_results (project_id);
CREATE INDEX IF NOT EXISTS idx_analysis_timestamp ON analysis_results (analysis_timestamp DESC);

-- Webhook events indexes
CREATE INDEX IF NOT EXISTS idx_webhook_events_status ON webhook_events (status);
CREATE INDEX IF NOT EXISTS idx_webhook_events_received ON webhook_events (received_at DESC);



-- =========================================================
-- Invoice smoothing adoption model - Phase 2 signals
-- =========================================================

DROP VIEW IF EXISTS public.vw_invoice_smoothing_global_signal_v1;
DROP MATERIALIZED VIEW IF EXISTS public.mv_invoice_smoothing_signal_v1 CASCADE;
DROP VIEW IF EXISTS public.vw_invoice_smoothing_signal_members_v1;
DROP VIEW IF EXISTS public.vw_invoice_smoothing_training_v1;
DROP FUNCTION IF EXISTS public.refresh_invoice_smoothing_signal_v1(DATE);
DROP FUNCTION IF EXISTS public.invoice_smoothing_signal_rows(DATE);
DROP FUNCTION IF EXISTS public.invoice_smoothing_signal_members(DATE);
DROP FUNCTION IF EXISTS public.invoice_smoothing_training_rows(DATE);

CREATE OR REPLACE FUNCTION public.invoice_smoothing_as_of_date()
RETURNS DATE AS $$
    SELECT COALESCE(
        NULLIF(current_setting('datacube.smoothing_as_of_date', true), '')::DATE,
        CURRENT_DATE
    );
$$ LANGUAGE sql STABLE;

CREATE OR REPLACE FUNCTION public.smoothing_normalize_token(raw_value TEXT)
RETURNS TEXT AS $$
    SELECT NULLIF(
        BTRIM(
            REGEXP_REPLACE(
                REGEXP_REPLACE(
                    REGEXP_REPLACE(
                        REGEXP_REPLACE(
                            REGEXP_REPLACE(
                                LOWER(BTRIM(COALESCE(raw_value, ''))),
                                '[[:space:]]*/[[:space:]]*', '/', 'g'
                            ),
                            '[[:space:]]*-[[:space:]]*', '-', 'g'
                        ),
                        '[[:space:]]*\([[:space:]]*', ' (', 'g'
                    ),
                    '[[:space:]]*\)[[:space:]]*', ')', 'g'
                ),
                '[[:space:]]+', ' ', 'g'
            )
        ),
        ''
    );
$$ LANGUAGE sql IMMUTABLE;

CREATE OR REPLACE FUNCTION public.invoice_smoothing_training_rows(
    p_as_of_date DATE DEFAULT CURRENT_DATE
)
RETURNS TABLE (
    as_of_date DATE,
    mature_cutoff_date DATE,
    project_id TEXT,
    project_name TEXT,
    category TEXT,
    type TEXT,
    raw_account_mirror TEXT,
    raw_product_mirror TEXT,
    first_date_invoiced DATE,
    last_date_invoiced DATE,
    invoicing_spread_days INTEGER,
    is_smoothed BOOLEAN,
    is_mature BOOLEAN
) AS $$
    SELECT
        COALESCE(p_as_of_date, CURRENT_DATE) AS as_of_date,
        (COALESCE(p_as_of_date, CURRENT_DATE) - INTERVAL '180 days')::DATE AS mature_cutoff_date,
        p.monday_id AS project_id,
        COALESCE(NULLIF(BTRIM(p.project_name), ''), p.item_name) AS project_name,
        NULLIF(BTRIM(p.category), '') AS category,
        NULLIF(BTRIM(p.type), '') AS type,
        NULLIF(BTRIM(p.account), '') AS raw_account_mirror,
        NULLIF(BTRIM(p.product_type), '') AS raw_product_mirror,
        p.first_date_invoiced,
        p.last_date_invoiced,
        p.invoicing_spread_days,
        (p.last_date_invoiced > p.first_date_invoiced) AS is_smoothed,
        (
            p.first_date_invoiced <=
            (COALESCE(p_as_of_date, CURRENT_DATE) - INTERVAL '180 days')::DATE
        ) AS is_mature
    FROM public.projects p
    WHERE p.first_date_invoiced IS NOT NULL
      AND p.last_date_invoiced IS NOT NULL;
$$ LANGUAGE sql STABLE;

CREATE OR REPLACE VIEW public.vw_invoice_smoothing_training_v1 AS
SELECT *
FROM public.invoice_smoothing_training_rows(public.invoice_smoothing_as_of_date()::DATE);

CREATE OR REPLACE FUNCTION public.invoice_smoothing_signal_members(
    p_as_of_date DATE DEFAULT CURRENT_DATE
)
RETURNS TABLE (
    as_of_date DATE,
    project_id TEXT,
    dimension TEXT,
    group_key TEXT,
    group_display TEXT
) AS $$
    WITH training AS (
        SELECT *
        FROM public.invoice_smoothing_training_rows(COALESCE(p_as_of_date, CURRENT_DATE)::DATE)
    ),
    raw_members AS (
        SELECT
            t.as_of_date AS member_as_of_date,
            t.project_id,
            'category'::TEXT AS dimension,
            public.smoothing_normalize_token(t.category) AS group_key,
            NULLIF(BTRIM(t.category), '') AS group_display
        FROM training t

        UNION ALL

        SELECT
            t.as_of_date,
            t.project_id,
            'type'::TEXT,
            public.smoothing_normalize_token(t.type),
            NULLIF(BTRIM(t.type), '')
        FROM training t

        UNION ALL

        SELECT
            t.as_of_date,
            t.project_id,
            'category_type'::TEXT,
            CONCAT(
                                public.smoothing_normalize_token(t.category),
                '|',
                                public.smoothing_normalize_token(t.type)
            ),
            CONCAT(NULLIF(BTRIM(t.category), ''), ' / ', NULLIF(BTRIM(t.type), ''))
        FROM training t
                WHERE public.smoothing_normalize_token(t.category) IS NOT NULL
                    AND public.smoothing_normalize_token(t.type) IS NOT NULL

        UNION ALL

        SELECT
            t.as_of_date,
            t.project_id,
            'product'::TEXT,
            public.smoothing_normalize_token(product_token.token),
            NULLIF(BTRIM(product_token.token), '')
        FROM training t
        CROSS JOIN LATERAL REGEXP_SPLIT_TO_TABLE(
            COALESCE(t.raw_product_mirror, ''),
            '[[:space:]]*,[[:space:]]*'
        ) AS product_token(token)

        UNION ALL

        SELECT
            t.as_of_date,
            t.project_id,
            'account'::TEXT,
            public.smoothing_normalize_token(account_token.token),
            NULLIF(BTRIM(account_token.token), '')
        FROM training t
        CROSS JOIN LATERAL REGEXP_SPLIT_TO_TABLE(
            COALESCE(t.raw_account_mirror, ''),
            '[[:space:]]*,[[:space:]]*'
        ) AS account_token(token)
    )
    SELECT
        rm.member_as_of_date AS as_of_date,
        rm.project_id,
        rm.dimension,
        rm.group_key,
        MIN(rm.group_display) AS group_display
    FROM raw_members rm
    WHERE rm.group_key IS NOT NULL
      AND rm.group_key <> ''
      AND rm.group_display IS NOT NULL
      AND rm.group_display <> ''
    GROUP BY
        rm.member_as_of_date,
        rm.project_id,
        rm.dimension,
        rm.group_key;
$$ LANGUAGE sql STABLE;

CREATE OR REPLACE VIEW public.vw_invoice_smoothing_signal_members_v1 AS
SELECT *
FROM public.invoice_smoothing_signal_members(public.invoice_smoothing_as_of_date()::DATE);

CREATE OR REPLACE FUNCTION public.invoice_smoothing_signal_rows(
    p_as_of_date DATE DEFAULT CURRENT_DATE
)
RETURNS TABLE (
    as_of_date DATE,
    dimension TEXT,
    group_key TEXT,
    group_display TEXT,
    all_project_count BIGINT,
    all_smoothed_count BIGINT,
    all_smoothed_pct NUMERIC(8,6),
    mature_project_count BIGINT,
    mature_smoothed_count BIGINT,
    mature_smoothed_pct NUMERIC(8,6),
    shrunk_mature_smoothed_pct NUMERIC(8,6),
    shrinkage_k INTEGER,
    mature_spread_days_sum NUMERIC(14,2),
    mature_avg_spread_days NUMERIC(10,2),
    mature_expected_spread_days NUMERIC(10,2),
    avg_spread_if_smoothed NUMERIC(10,2),
    median_smoothed_days NUMERIC(10,2),
    p75_smoothed_days NUMERIC(10,2),
    rate_90_plus_days NUMERIC(8,6),
    rate_180_plus_days NUMERIC(8,6),
    confidence TEXT,
    suggested_use TEXT
) AS $$
    WITH training AS (
        SELECT *
        FROM public.invoice_smoothing_training_rows(COALESCE(p_as_of_date, CURRENT_DATE)::DATE)
    ),
    members AS (
        SELECT *
        FROM public.invoice_smoothing_signal_members(COALESCE(p_as_of_date, CURRENT_DATE)::DATE)
    ),
    member_rows AS (
        SELECT
            m.as_of_date,
            m.dimension,
            m.group_key,
            m.group_display,
            t.project_id,
            t.invoicing_spread_days,
            t.is_smoothed,
            t.is_mature
        FROM members m
        INNER JOIN training t
            ON t.as_of_date = m.as_of_date
           AND t.project_id = m.project_id
    ),
    global_stats AS (
        SELECT
            COUNT(*) AS global_all_project_count,
            COUNT(*) FILTER (WHERE t.is_smoothed) AS global_all_smoothed_count,
            COUNT(*) FILTER (WHERE t.is_mature) AS global_mature_project_count,
            COUNT(*) FILTER (WHERE t.is_mature AND t.is_smoothed) AS global_mature_smoothed_count,
            COUNT(*) FILTER (
                WHERE t.is_mature AND t.invoicing_spread_days >= 90
            ) AS global_mature_90_plus_count,
            COUNT(*) FILTER (
                WHERE t.is_mature AND t.invoicing_spread_days >= 180
            ) AS global_mature_180_plus_count,
            COALESCE(
                SUM(t.invoicing_spread_days) FILTER (WHERE t.is_mature),
                0
            )::NUMERIC AS global_mature_spread_days_sum,
            AVG(t.invoicing_spread_days::NUMERIC) FILTER (WHERE t.is_mature) AS global_mature_avg_spread_days_raw,
            AVG(t.invoicing_spread_days::NUMERIC) FILTER (
                WHERE t.is_mature AND t.is_smoothed
            ) AS global_avg_spread_if_smoothed,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY t.invoicing_spread_days)
                FILTER (WHERE t.is_mature AND t.is_smoothed) AS global_median_smoothed_days,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY t.invoicing_spread_days)
                FILTER (WHERE t.is_mature AND t.is_smoothed) AS global_p75_smoothed_days
        FROM training t
    ),
    global_rates AS (
        SELECT
            gs.*,
            CASE
                WHEN gs.global_mature_project_count > 0 THEN
                    gs.global_mature_smoothed_count::NUMERIC / gs.global_mature_project_count
                ELSE 0::NUMERIC
            END AS global_mature_rate,
            CASE
                WHEN gs.global_mature_project_count > 0 THEN
                    gs.global_mature_spread_days_sum / gs.global_mature_project_count
                ELSE 0::NUMERIC
            END AS global_mature_avg_spread_days
        FROM global_stats gs
    ),
    group_stats AS (
        SELECT
            mr.as_of_date,
            mr.dimension,
            mr.group_key,
            MIN(mr.group_display) AS group_display,
            COUNT(DISTINCT mr.project_id) AS all_project_count,
            COUNT(DISTINCT mr.project_id) FILTER (WHERE mr.is_smoothed) AS all_smoothed_count,
            COUNT(DISTINCT mr.project_id) FILTER (WHERE mr.is_mature) AS mature_project_count,
            COUNT(DISTINCT mr.project_id) FILTER (WHERE mr.is_mature AND mr.is_smoothed) AS mature_smoothed_count,
            COUNT(DISTINCT mr.project_id) FILTER (
                WHERE mr.is_mature AND mr.invoicing_spread_days >= 90
            ) AS mature_90_plus_count,
            COUNT(DISTINCT mr.project_id) FILTER (
                WHERE mr.is_mature AND mr.invoicing_spread_days >= 180
            ) AS mature_180_plus_count,
            COALESCE(
                SUM(mr.invoicing_spread_days) FILTER (WHERE mr.is_mature),
                0
            )::NUMERIC AS mature_spread_days_sum,
            AVG(mr.invoicing_spread_days::NUMERIC) FILTER (WHERE mr.is_mature) AS mature_avg_spread_days,
            AVG(mr.invoicing_spread_days::NUMERIC) FILTER (
                WHERE mr.is_mature AND mr.is_smoothed
            ) AS avg_spread_if_smoothed,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY mr.invoicing_spread_days)
                FILTER (WHERE mr.is_mature AND mr.is_smoothed) AS median_smoothed_days,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY mr.invoicing_spread_days)
                FILTER (WHERE mr.is_mature AND mr.is_smoothed) AS p75_smoothed_days
        FROM member_rows mr
        GROUP BY mr.as_of_date, mr.dimension, mr.group_key
    )
    SELECT
        gs.as_of_date,
        gs.dimension,
        gs.group_key,
        gs.group_display,
        gs.all_project_count,
        gs.all_smoothed_count,
        ROUND(
            COALESCE(gs.all_smoothed_count::NUMERIC / NULLIF(gs.all_project_count, 0), 0),
            6
        )::NUMERIC(8,6) AS all_smoothed_pct,
        gs.mature_project_count,
        gs.mature_smoothed_count,
        ROUND(
            COALESCE(gs.mature_smoothed_count::NUMERIC / NULLIF(gs.mature_project_count, 0), 0),
            6
        )::NUMERIC(8,6) AS mature_smoothed_pct,
        ROUND(
            (
                gs.mature_smoothed_count::NUMERIC +
                (20::NUMERIC * gr.global_mature_rate)
            ) / (gs.mature_project_count + 20),
            6
        )::NUMERIC(8,6) AS shrunk_mature_smoothed_pct,
        20::INTEGER AS shrinkage_k,
        ROUND(gs.mature_spread_days_sum, 2)::NUMERIC(14,2) AS mature_spread_days_sum,
        ROUND(COALESCE(gs.mature_avg_spread_days, 0), 2)::NUMERIC(10,2) AS mature_avg_spread_days,
        ROUND(
            (
                gs.mature_spread_days_sum +
                (20::NUMERIC * gr.global_mature_avg_spread_days)
            ) / (gs.mature_project_count + 20),
            2
        )::NUMERIC(10,2) AS mature_expected_spread_days,
        ROUND(COALESCE(gs.avg_spread_if_smoothed, 0), 2)::NUMERIC(10,2) AS avg_spread_if_smoothed,
        ROUND(COALESCE(gs.median_smoothed_days, 0)::NUMERIC, 2)::NUMERIC(10,2) AS median_smoothed_days,
        ROUND(COALESCE(gs.p75_smoothed_days, 0)::NUMERIC, 2)::NUMERIC(10,2) AS p75_smoothed_days,
        ROUND(
            COALESCE(gs.mature_90_plus_count::NUMERIC / NULLIF(gs.mature_project_count, 0), 0),
            6
        )::NUMERIC(8,6) AS rate_90_plus_days,
        ROUND(
            COALESCE(gs.mature_180_plus_count::NUMERIC / NULLIF(gs.mature_project_count, 0), 0),
            6
        )::NUMERIC(8,6) AS rate_180_plus_days,
        CASE
            WHEN gs.mature_project_count >= 50 THEN 'High'
            WHEN gs.mature_project_count >= 15 THEN 'Medium'
            WHEN gs.mature_project_count >= 5 THEN 'Low'
            ELSE 'Very low'
        END AS confidence,
        CASE
            WHEN gs.mature_project_count >= 50 THEN 'Use directly'
            WHEN gs.mature_project_count >= 15 THEN 'Use with shrinkage'
            WHEN gs.mature_project_count >= 5 THEN 'Directional only'
            ELSE 'Use global fallback'
        END AS suggested_use
    FROM group_stats gs
    CROSS JOIN global_rates gr

    UNION ALL

    SELECT
        COALESCE(p_as_of_date, CURRENT_DATE) AS as_of_date,
        'global'::TEXT AS dimension,
        '__global__'::TEXT AS group_key,
        'Global mature fallback'::TEXT AS group_display,
        gr.global_all_project_count AS all_project_count,
        gr.global_all_smoothed_count AS all_smoothed_count,
        ROUND(
            COALESCE(gr.global_all_smoothed_count::NUMERIC / NULLIF(gr.global_all_project_count, 0), 0),
            6
        )::NUMERIC(8,6) AS all_smoothed_pct,
        gr.global_mature_project_count AS mature_project_count,
        gr.global_mature_smoothed_count AS mature_smoothed_count,
        ROUND(gr.global_mature_rate, 6)::NUMERIC(8,6) AS mature_smoothed_pct,
        ROUND(gr.global_mature_rate, 6)::NUMERIC(8,6) AS shrunk_mature_smoothed_pct,
        20::INTEGER AS shrinkage_k,
        ROUND(gr.global_mature_spread_days_sum, 2)::NUMERIC(14,2) AS mature_spread_days_sum,
        ROUND(COALESCE(gr.global_mature_avg_spread_days_raw, 0), 2)::NUMERIC(10,2) AS mature_avg_spread_days,
        ROUND(gr.global_mature_avg_spread_days, 2)::NUMERIC(10,2) AS mature_expected_spread_days,
        ROUND(COALESCE(gr.global_avg_spread_if_smoothed, 0), 2)::NUMERIC(10,2) AS avg_spread_if_smoothed,
        ROUND(COALESCE(gr.global_median_smoothed_days, 0)::NUMERIC, 2)::NUMERIC(10,2) AS median_smoothed_days,
        ROUND(COALESCE(gr.global_p75_smoothed_days, 0)::NUMERIC, 2)::NUMERIC(10,2) AS p75_smoothed_days,
        ROUND(
            COALESCE(gr.global_mature_90_plus_count::NUMERIC / NULLIF(gr.global_mature_project_count, 0), 0),
            6
        )::NUMERIC(8,6) AS rate_90_plus_days,
        ROUND(
            COALESCE(gr.global_mature_180_plus_count::NUMERIC / NULLIF(gr.global_mature_project_count, 0), 0),
            6
        )::NUMERIC(8,6) AS rate_180_plus_days,
        CASE
            WHEN gr.global_mature_project_count >= 50 THEN 'High'
            WHEN gr.global_mature_project_count >= 15 THEN 'Medium'
            WHEN gr.global_mature_project_count >= 5 THEN 'Low'
            ELSE 'Very low'
        END AS confidence,
        'Global fallback'::TEXT AS suggested_use
    FROM global_rates gr;
$$ LANGUAGE sql STABLE;

CREATE MATERIALIZED VIEW public.mv_invoice_smoothing_signal_v1 AS
SELECT *
FROM public.invoice_smoothing_signal_rows(public.invoice_smoothing_as_of_date()::DATE);

CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_invoice_smoothing_signal_v1_unique
    ON public.mv_invoice_smoothing_signal_v1 (as_of_date, dimension, group_key);

CREATE INDEX IF NOT EXISTS idx_mv_invoice_smoothing_signal_v1_dimension
    ON public.mv_invoice_smoothing_signal_v1 (dimension, group_key);

CREATE INDEX IF NOT EXISTS idx_mv_invoice_smoothing_signal_v1_confidence
    ON public.mv_invoice_smoothing_signal_v1 (confidence, mature_project_count);

CREATE OR REPLACE FUNCTION public.refresh_invoice_smoothing_signal_v1(
    p_as_of_date DATE DEFAULT CURRENT_DATE
)
RETURNS DATE AS $$
DECLARE
    target_as_of_date DATE := COALESCE(p_as_of_date, CURRENT_DATE);
BEGIN
    PERFORM set_config('datacube.smoothing_as_of_date', target_as_of_date::TEXT, true);
    REFRESH MATERIALIZED VIEW public.mv_invoice_smoothing_signal_v1;
    RETURN target_as_of_date;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE VIEW public.vw_invoice_smoothing_global_signal_v1 AS
SELECT *
FROM public.mv_invoice_smoothing_signal_v1
WHERE dimension = 'global'
  AND group_key = '__global__';

COMMENT ON VIEW public.vw_invoice_smoothing_training_v1 IS
    'Phase 2 invoice smoothing training rows using the session as_of date or CURRENT_DATE.';

COMMENT ON VIEW public.vw_invoice_smoothing_signal_members_v1 IS
    'Distinct project membership rows for smoothing dimensions; product/account mirrors are tokenized once per project.';

COMMENT ON MATERIALIZED VIEW public.mv_invoice_smoothing_signal_v1 IS
    'Phase 2 Empirical-Bayes invoice smoothing signal metrics by dimension and group.';

COMMENT ON VIEW public.vw_invoice_smoothing_global_signal_v1 IS
    'Live database-derived global mature fallback row for invoice smoothing signals.';

-- ===========================================================


-- Create views for common queries
CREATE VIEW project_analytics AS
SELECT 
    p.*,
    COUNT(s.id) as subitem_count,
    SUM(s.quote_amount) as total_quote_value,
    AVG(s.quote_amount) as avg_quote_value
FROM projects p
LEFT JOIN subitems s ON p.monday_id = s.parent_monday_id
GROUP BY p.id;


-- =========================================================
-- Add product_key column to projects table
-- =========================================================

ALTER TABLE projects ADD COLUMN IF NOT EXISTS product_key TEXT;

CREATE INDEX IF NOT EXISTS idx_projects_product_key ON projects (product_key);
CREATE INDEX IF NOT EXISTS idx_projects_segment_keys ON projects (account, type, category, product_key);

-- Temporary default for existing rows (backfill script will compute proper values)
UPDATE projects SET product_key = 'unknown' WHERE product_key IS NULL;



-- =========================================================
-- Rebuild conversion_metrics (5-year window)
-- =========================================================

-- Create materialized view for performance metrics
-- Use closed-won only as the "won" population
DROP MATERIALIZED VIEW IF EXISTS conversion_metrics CASCADE;

CREATE MATERIALIZED VIEW conversion_metrics AS
SELECT
    NULLIF(TRIM(account), '')        AS account,
    NULLIF(TRIM(type), '')           AS type,
    NULLIF(TRIM(category), '')       AS category,
    NULLIF(TRIM(product_type), '')   AS product_type,
    NULLIF(TRIM(product_key), '')    AS product_key,
    COUNT(*)                         AS total_projects,
    COUNT(*) FILTER (WHERE pipeline_stage = 'Won - Closed (Invoiced)')                          AS won_projects,
    COUNT(*) FILTER (WHERE pipeline_stage = 'Lost')                                             AS lost_projects,
    COUNT(*) FILTER (WHERE pipeline_stage NOT IN ('Won - Closed (Invoiced)', 'Lost'))           AS open_projects,
    ROUND(
        COUNT(*) FILTER (WHERE pipeline_stage = 'Won - Closed (Invoiced)')::numeric /
        NULLIF(COUNT(*), 0),
        3
    ) AS win_rate,
    ROUND(
        COUNT(*) FILTER (WHERE pipeline_stage = 'Won - Closed (Invoiced)')::numeric /
        NULLIF(COUNT(*) FILTER (WHERE pipeline_stage IN ('Won - Closed (Invoiced)', 'Lost')), 0),
        3
    ) AS closed_win_rate,
    AVG(gestation_period) FILTER (WHERE gestation_period > 0)                                   AS avg_gestation,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY gestation_period)
        FILTER (WHERE gestation_period > 0)                                                     AS gestation_p25,
    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY gestation_period)
        FILTER (WHERE gestation_period > 0)                                                     AS median_gestation,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY gestation_period)
        FILTER (WHERE gestation_period > 0)                                                     AS gestation_p75
FROM projects
WHERE date_created >= CURRENT_DATE - INTERVAL '5 years'
GROUP BY 1, 2, 3, 4, 5;

CREATE UNIQUE INDEX IF NOT EXISTS conversion_metrics_unique
    ON conversion_metrics (account, type, category, product_type, product_key);

-- Index for queries that segment by product_key only
CREATE INDEX IF NOT EXISTS idx_conversion_metrics_product_key
    ON conversion_metrics (account, type, category, product_key);

-- =========================================================
-- Rebuild conversion_metrics_recent (2-year window)
-- =========================================================


DROP MATERIALIZED VIEW IF EXISTS conversion_metrics_recent CASCADE;

CREATE MATERIALIZED VIEW conversion_metrics_recent AS
SELECT
    NULLIF(TRIM(account), '')        AS account,
    NULLIF(TRIM(type), '')           AS type,
    NULLIF(TRIM(category), '')       AS category,
    NULLIF(TRIM(product_type), '')   AS product_type,
    NULLIF(TRIM(product_key), '')    AS product_key,
    COUNT(*)                         AS total_projects,
    COUNT(*) FILTER (WHERE pipeline_stage = 'Won - Closed (Invoiced)')                          AS won_projects,
    COUNT(*) FILTER (WHERE pipeline_stage = 'Lost')                                             AS lost_projects,
    COUNT(*) FILTER (WHERE pipeline_stage NOT IN ('Won - Closed (Invoiced)', 'Lost'))           AS open_projects,
    ROUND(
        COUNT(*) FILTER (WHERE pipeline_stage = 'Won - Closed (Invoiced)')::numeric /
        NULLIF(COUNT(*), 0),
        3
    ) AS win_rate,
    ROUND(
        COUNT(*) FILTER (WHERE pipeline_stage = 'Won - Closed (Invoiced)')::numeric /
        NULLIF(COUNT(*) FILTER (WHERE pipeline_stage IN ('Won - Closed (Invoiced)', 'Lost')), 0),
        3
    ) AS closed_win_rate,
    AVG(gestation_period) FILTER (WHERE gestation_period > 0)                                   AS avg_gestation,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY gestation_period)
        FILTER (WHERE gestation_period > 0)                                                     AS gestation_p25,
    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY gestation_period)
        FILTER (WHERE gestation_period > 0)                                                     AS median_gestation,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY gestation_period)
        FILTER (WHERE gestation_period > 0)                                                     AS gestation_p75
FROM projects
WHERE date_created >= CURRENT_DATE - INTERVAL '2 years'
GROUP BY 1, 2, 3, 4, 5;

CREATE UNIQUE INDEX IF NOT EXISTS conversion_metrics_recent_unique
    ON conversion_metrics_recent (account, type, category, product_type, product_key);

CREATE INDEX IF NOT EXISTS idx_conversion_metrics_recent_product_key
    ON conversion_metrics_recent (account, type, category, product_key);

-- ==================================================================

-- Create index for full-text search
CREATE INDEX idx_projects_search ON projects USING gin(
    to_tsvector('english', 
        COALESCE(project_name, '') || ' ' || 
        COALESCE(account, '') || ' ' || 
        COALESCE(category, '')
    )
);

-- Row Level Security (RLS) policies
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE subitems ENABLE ROW LEVEL SECURITY;
ALTER TABLE hidden_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE analysis_results ENABLE ROW LEVEL SECURITY;


-- Migration: Track order values 
ALTER TABLE hidden_items
  ADD COLUMN IF NOT EXISTS date_order_received DATE;
ALTER TABLE hidden_items
  ADD COLUMN IF NOT EXISTS cust_order_value_material NUMERIC(12, 2);

ALTER TABLE subitems
  ADD COLUMN IF NOT EXISTS cust_order_value_material NUMERIC(12, 2);

ALTER TABLE projects
  ADD COLUMN IF NOT EXISTS total_order_value NUMERIC(12, 2);
ALTER TABLE projects
  ADD COLUMN IF NOT EXISTS date_order_received DATE;

-- Create policies (adjust based on your auth strategy)
CREATE POLICY "Enable read access for authenticated users" ON projects
    FOR SELECT USING (true);

CREATE POLICY "Enable write access for service role" ON projects
    FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');

-- Triggers for updated_at
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_projects_updated_at
    BEFORE UPDATE ON projects
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER update_subitems_updated_at
    BEFORE UPDATE ON subitems
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();



-- Enforce one row per project
ALTER TABLE analysis_results
  ADD CONSTRAINT IF NOT EXISTS analysis_results_project_unique UNIQUE (project_id);

-- Migration (run on your Supabase/Postgres)
ALTER TABLE analysis_results
  DROP CONSTRAINT IF EXISTS analysis_results_rating_score_check;

ALTER TABLE analysis_results
  ADD CONSTRAINT analysis_results_rating_score_check
  CHECK (rating_score >= 1 AND rating_score <= 100);

-- Optional backfill to scale existing 1–10 scores up to 1–100:
UPDATE analysis_results
SET rating_score = 1 + ((rating_score - 1) * 11)
WHERE rating_score BETWEEN 1 AND 10;

-- Queue job tracking
CREATE TABLE IF NOT EXISTS job_queue (
    id UUID PRIMARY KEY,
    job_type TEXT NOT NULL,
    project_id TEXT,
    status TEXT NOT NULL,
    attempts INTEGER DEFAULT 0,
    payload JSONB,
    detail TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_job_queue_status ON job_queue (status);
CREATE INDEX IF NOT EXISTS idx_job_queue_project ON job_queue (project_id);

CREATE TRIGGER update_job_queue_timestamp
    BEFORE UPDATE ON job_queue
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();


-- =========================================================
-- Pipeline Forecast Snapshot Table
-- =========================================================

CREATE TABLE IF NOT EXISTS pipeline_forecast_snapshot (
    snapshot_date DATE NOT NULL,
    project_id TEXT NOT NULL,
    forecast_month DATE NOT NULL,
    stage_bucket TEXT NOT NULL,
    contract_value NUMERIC(12,2) NOT NULL DEFAULT 0,
    probability NUMERIC(6,5) NOT NULL DEFAULT 0,
    committed_value NUMERIC(12,2) NOT NULL DEFAULT 0,
    expected_value NUMERIC(12,2) NOT NULL DEFAULT 0,
    best_case_value NUMERIC(12,2) NOT NULL DEFAULT 0,
    worst_case_value NUMERIC(12,2) NOT NULL DEFAULT 0,
    analysis_timestamp TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (snapshot_date, project_id, forecast_month)
);

CREATE INDEX IF NOT EXISTS idx_pipeline_forecast_snapshot_snapshot_date
    ON pipeline_forecast_snapshot (snapshot_date);

CREATE INDEX IF NOT EXISTS idx_pipeline_forecast_snapshot_forecast_month
    ON pipeline_forecast_snapshot (forecast_month);

CREATE INDEX IF NOT EXISTS idx_pipeline_forecast_snapshot_project_id
    ON pipeline_forecast_snapshot (project_id);

CREATE INDEX IF NOT EXISTS idx_pipeline_forecast_snapshot_snapshot_forecast
    ON pipeline_forecast_snapshot (snapshot_date, forecast_month);


-- =========================================================
-- Pipeline Smoothing Forecast Snapshot Table
-- =========================================================

CREATE TABLE IF NOT EXISTS pipeline_smoothing_forecast_snapshot (
    snapshot_date DATE NOT NULL,
    snapshot_timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    project_id TEXT NOT NULL,
    forecast_month DATE NOT NULL,
    stage_bucket TEXT NOT NULL,
    base_forecast_month DATE NOT NULL,
    forecast_date DATE NOT NULL,
    smoothing_as_of_date DATE,
    forecast_value_net NUMERIC(18,2) NOT NULL DEFAULT 0,
    forecast_value_gross NUMERIC(18,2) NOT NULL DEFAULT 0,
    expected_value NUMERIC(12,2) NOT NULL DEFAULT 0,
    combined_smoothed_probability NUMERIC(8,6) NOT NULL DEFAULT 0,
    expected_spread_days NUMERIC(10,2) NOT NULL DEFAULT 0,
    risk_band TEXT,
    workbook_suggested_treatment TEXT,
    default_smoothing_recommended BOOLEAN,
    unsmoothed_allocated_value NUMERIC(12,2) NOT NULL DEFAULT 0,
    smoothed_allocated_value NUMERIC(12,2) NOT NULL DEFAULT 0,
    allocated_expected_value NUMERIC(12,2) NOT NULL DEFAULT 0,
    project_count INTEGER NOT NULL DEFAULT 1,
    source_view TEXT NOT NULL DEFAULT 'vw_pipeline_smoothing_score_v1',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (snapshot_date, project_id, forecast_month)
);

ALTER TABLE pipeline_smoothing_forecast_snapshot
    ADD COLUMN IF NOT EXISTS snapshot_date DATE DEFAULT CURRENT_DATE,
    ADD COLUMN IF NOT EXISTS snapshot_timestamp TIMESTAMPTZ DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS project_id TEXT DEFAULT '__monthly_total__',
    ADD COLUMN IF NOT EXISTS forecast_month DATE DEFAULT DATE_TRUNC('month', CURRENT_DATE)::DATE,
    ADD COLUMN IF NOT EXISTS stage_bucket TEXT DEFAULT 'All',
    ADD COLUMN IF NOT EXISTS base_forecast_month DATE DEFAULT DATE_TRUNC('month', CURRENT_DATE)::DATE,
    ADD COLUMN IF NOT EXISTS forecast_date DATE DEFAULT CURRENT_DATE,
    ADD COLUMN IF NOT EXISTS smoothing_as_of_date DATE,
    ADD COLUMN IF NOT EXISTS forecast_value_net NUMERIC(18,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS forecast_value_gross NUMERIC(18,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS expected_value NUMERIC(12,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS combined_smoothed_probability NUMERIC(8,6) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS expected_spread_days NUMERIC(10,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS risk_band TEXT,
    ADD COLUMN IF NOT EXISTS workbook_suggested_treatment TEXT,
    ADD COLUMN IF NOT EXISTS default_smoothing_recommended BOOLEAN,
    ADD COLUMN IF NOT EXISTS unsmoothed_allocated_value NUMERIC(12,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS smoothed_allocated_value NUMERIC(12,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS allocated_expected_value NUMERIC(12,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS project_count INTEGER DEFAULT 1,
    ADD COLUMN IF NOT EXISTS source_view TEXT DEFAULT 'vw_pipeline_smoothing_score_v1';

UPDATE pipeline_smoothing_forecast_snapshot
SET
    snapshot_date = COALESCE(snapshot_date, snapshot_timestamp::DATE, CURRENT_DATE),
    snapshot_timestamp = COALESCE(snapshot_timestamp, created_at, NOW()),
    project_id = COALESCE(project_id, '__monthly_total__'),
    forecast_month = COALESCE(forecast_month, DATE_TRUNC('month', CURRENT_DATE)::DATE),
    stage_bucket = COALESCE(stage_bucket, 'All'),
    base_forecast_month = COALESCE(base_forecast_month, forecast_month),
    forecast_date = COALESCE(forecast_date, forecast_month, CURRENT_DATE),
    forecast_value_net = COALESCE(forecast_value_net, allocated_expected_value, expected_value, 0),
    forecast_value_gross = COALESCE(forecast_value_gross, allocated_expected_value, expected_value, 0),
    expected_value = COALESCE(expected_value, allocated_expected_value, forecast_value_net, 0),
    combined_smoothed_probability = COALESCE(combined_smoothed_probability, 0),
    expected_spread_days = COALESCE(expected_spread_days, 0),
    unsmoothed_allocated_value = COALESCE(unsmoothed_allocated_value, 0),
    smoothed_allocated_value = COALESCE(smoothed_allocated_value, forecast_value_net, 0),
    allocated_expected_value = COALESCE(allocated_expected_value, forecast_value_net, expected_value, 0),
    project_count = COALESCE(project_count, 1),
    source_view = COALESCE(source_view, 'vw_pipeline_smoothing_score_v1')
WHERE snapshot_date IS NULL
   OR snapshot_timestamp IS NULL
   OR project_id IS NULL
   OR forecast_month IS NULL
   OR stage_bucket IS NULL
   OR base_forecast_month IS NULL
   OR forecast_date IS NULL
   OR forecast_value_net IS NULL
   OR forecast_value_gross IS NULL
   OR expected_value IS NULL
   OR combined_smoothed_probability IS NULL
   OR expected_spread_days IS NULL
   OR unsmoothed_allocated_value IS NULL
   OR smoothed_allocated_value IS NULL
   OR allocated_expected_value IS NULL
   OR project_count IS NULL
   OR source_view IS NULL;

ALTER TABLE pipeline_smoothing_forecast_snapshot
    ALTER COLUMN snapshot_date SET NOT NULL,
    ALTER COLUMN snapshot_timestamp SET NOT NULL,
    ALTER COLUMN project_id SET NOT NULL,
    ALTER COLUMN forecast_month SET NOT NULL,
    ALTER COLUMN stage_bucket SET NOT NULL,
    ALTER COLUMN base_forecast_month SET NOT NULL,
    ALTER COLUMN forecast_date SET NOT NULL,
    ALTER COLUMN forecast_value_net SET NOT NULL,
    ALTER COLUMN forecast_value_gross SET NOT NULL,
    ALTER COLUMN expected_value SET NOT NULL,
    ALTER COLUMN combined_smoothed_probability SET NOT NULL,
    ALTER COLUMN expected_spread_days SET NOT NULL,
    ALTER COLUMN unsmoothed_allocated_value SET NOT NULL,
    ALTER COLUMN smoothed_allocated_value SET NOT NULL,
    ALTER COLUMN allocated_expected_value SET NOT NULL,
    ALTER COLUMN project_count SET NOT NULL,
    ALTER COLUMN source_view SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_pipeline_smoothing_forecast_snapshot_unique
    ON pipeline_smoothing_forecast_snapshot (snapshot_date, project_id, forecast_month);

CREATE INDEX IF NOT EXISTS idx_pipeline_smoothing_forecast_snapshot_snapshot_date
    ON pipeline_smoothing_forecast_snapshot (snapshot_date);

CREATE INDEX IF NOT EXISTS idx_pipeline_smoothing_forecast_snapshot_forecast_month
    ON pipeline_smoothing_forecast_snapshot (forecast_month);

CREATE INDEX IF NOT EXISTS idx_pipeline_smoothing_forecast_snapshot_project_id
    ON pipeline_smoothing_forecast_snapshot (project_id);

CREATE INDEX IF NOT EXISTS idx_pipeline_smoothing_forecast_snapshot_snapshot_forecast
    ON pipeline_smoothing_forecast_snapshot (snapshot_date, forecast_month);


###############################

-- =========================================================
-- Forecast artifacts rebuild (correct dependency order)
-- =========================================================

-- Drop dependent artifact first, then base view
DROP MATERIALIZED VIEW IF EXISTS mv_pipeline_smoothed_revenue_monthly_12m_v1 CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_pipeline_forecast_monthly_12m_v1 CASCADE;
DROP VIEW IF EXISTS vw_pipeline_smoothing_score_v1;
DROP VIEW IF EXISTS vw_pipeline_forecast_project_v1;

-- =========================================================
-- Stage 1 + Stage 3: Project-level forecast artifact (centralized formulas)
-- =========================================================

CREATE VIEW vw_pipeline_forecast_project_v1 AS
WITH latest_analysis AS (
    SELECT
        ar.project_id,
        ar.analysis_timestamp,
        ar.expected_gestation_days,
        ar.expected_conversion_rate,
        ar.conversion_confidence,
        ar.rating_score,
        ROW_NUMBER() OVER (
            PARTITION BY ar.project_id
            ORDER BY ar.analysis_timestamp DESC NULLS LAST, ar.id DESC
        ) AS rn
    FROM analysis_results ar
),
project_base AS (
    SELECT
        p.id AS project_uuid,
        p.monday_id AS project_id,
        p.item_name,
        COALESCE(NULLIF(p.project_name, ''), p.item_name) AS project_name,
        p.account,
        p.type,
        p.category,
        p.product_type,
        p.product_key,

        p.pipeline_stage,

        CASE
            WHEN p.pipeline_stage IN ('Won - Closed (Invoiced)', 'Won - Open (Order Received)', 'Won Via Other Ref') THEN 'Committed'
            WHEN p.pipeline_stage = 'Lost' THEN 'Lost'
            ELSE 'Open'
        END AS stage_bucket,

        CASE
            WHEN p.pipeline_stage IN ('Won - Closed (Invoiced)', 'Won - Open (Order Received)', 'Won Via Other Ref')
                THEN COALESCE(NULLIF(p.total_order_value, 0), NULLIF(p.new_enquiry_value, 0), 0)
            WHEN p.pipeline_stage = 'Lost'
                THEN COALESCE(NULLIF(p.new_enquiry_value, 0), NULLIF(p.total_order_value, 0), 0)
            ELSE
                COALESCE(NULLIF(p.new_enquiry_value, 0), NULLIF(p.total_order_value, 0), 0)
        END::NUMERIC(12,2) AS contract_value,

        p.total_order_value,
        p.new_enquiry_value,
        p.probability_percent,
        p.date_order_received,
        p.expected_start_date,
        p.date_created,

        la.analysis_timestamp,
        la.expected_gestation_days,
        la.expected_conversion_rate,
        la.conversion_confidence,
        la.rating_score,

        CASE
            WHEN p.date_order_received IS NOT NULL THEN p.date_order_received
            WHEN p.date_created IS NOT NULL AND la.expected_gestation_days IS NOT NULL
                THEN (p.date_created + GREATEST(la.expected_gestation_days, 0))
            WHEN p.expected_start_date IS NOT NULL THEN p.expected_start_date
            WHEN p.date_created IS NOT NULL THEN p.date_created
            ELSE CURRENT_DATE
        END AS forecast_date,

        CASE
            WHEN p.date_order_received IS NOT NULL THEN 'date_order_received'
            WHEN p.date_created IS NOT NULL AND la.expected_gestation_days IS NOT NULL THEN 'date_created_plus_expected_gestation_days'
            WHEN p.expected_start_date IS NOT NULL THEN 'expected_start_date'
            WHEN p.date_created IS NOT NULL THEN 'date_created'
            ELSE 'current_date_default'
        END AS forecast_date_source
    FROM projects p
    LEFT JOIN latest_analysis la
        ON la.project_id = p.monday_id
       AND la.rn = 1
),
probability_base AS (
    SELECT
        pb.*,

        GREATEST(
            0.0::NUMERIC,
            LEAST(
                1.0::NUMERIC,
                CASE
                    WHEN pb.stage_bucket = 'Lost' THEN 0.0
                    WHEN pb.stage_bucket = 'Committed' THEN 1.0
                    WHEN pb.expected_conversion_rate IS NOT NULL THEN pb.expected_conversion_rate
                    WHEN pb.probability_percent IS NOT NULL THEN (pb.probability_percent::NUMERIC / 100.0)
                    ELSE
                        CASE pb.pipeline_stage
                            WHEN 'Customer Confident Of Project Success' THEN 0.20
                            WHEN 'Customer Has Order' THEN 0.50
                            WHEN 'Customer Has Order - TP Preferred Supplier' THEN 0.75
                            WHEN 'Open Enquiry' THEN 0.00
                            WHEN 'Check with IS' THEN 0.30
                            ELSE 0.50
                        END
                END
            )
        ) AS probability,

        CASE
            WHEN pb.conversion_confidence IS NOT NULL AND pb.conversion_confidence > 0 THEN
                LEAST(
                    0.35::NUMERIC,
                    GREATEST(0.05::NUMERIC, (1.0::NUMERIC - pb.conversion_confidence) * 0.30::NUMERIC)
                )
            ELSE
                CASE pb.pipeline_stage
                    WHEN 'Customer Has Order - TP Preferred Supplier' THEN 0.08::NUMERIC
                    WHEN 'Customer Has Order' THEN 0.12::NUMERIC
                    WHEN 'Customer Confident Of Project Success' THEN 0.18::NUMERIC
                    WHEN 'Check with IS' THEN 0.20::NUMERIC
                    WHEN 'Open Enquiry' THEN 0.25::NUMERIC
                    ELSE 0.15::NUMERIC
                END
        END AS probability_spread
    FROM project_base pb
),
project_bands AS (
    SELECT
        p.*,

        CASE
            WHEN p.stage_bucket = 'Committed' THEN 1.0::NUMERIC
            WHEN p.stage_bucket = 'Lost' THEN 0.0::NUMERIC
            ELSE GREATEST(0.0::NUMERIC, LEAST(1.0::NUMERIC, p.probability + p.probability_spread))
        END AS best_case_probability,

        CASE
            WHEN p.stage_bucket = 'Committed' THEN 1.0::NUMERIC
            WHEN p.stage_bucket = 'Lost' THEN 0.0::NUMERIC
            ELSE GREATEST(0.0::NUMERIC, LEAST(1.0::NUMERIC, p.probability - p.probability_spread))
        END AS worst_case_probability
    FROM probability_base p
)
SELECT
    b.project_uuid,
    b.project_id,
    b.item_name,
    b.project_name,
    b.account,
    b.type,
    b.category,
    b.product_type,
    b.product_key,
    b.pipeline_stage,
    b.stage_bucket,
    b.contract_value,
    b.total_order_value,
    b.new_enquiry_value,
    b.date_created,
    b.probability,

    b.forecast_date,
    DATE_TRUNC('month', b.forecast_date)::DATE AS forecast_month,
    b.forecast_date_source,

    b.analysis_timestamp,
    b.expected_gestation_days,
    b.expected_conversion_rate,
    b.conversion_confidence,
    b.rating_score,
    b.probability_percent,

    ROUND(
        CASE WHEN b.stage_bucket = 'Committed' THEN b.contract_value ELSE 0::NUMERIC END,
        2
    )::NUMERIC(12,2) AS committed_value,

    ROUND((b.contract_value * b.probability)::NUMERIC, 2)::NUMERIC(12,2) AS expected_value,
    ROUND((b.contract_value * b.best_case_probability)::NUMERIC, 2)::NUMERIC(12,2) AS best_case_value,
    ROUND((b.contract_value * b.worst_case_probability)::NUMERIC, 2)::NUMERIC(12,2) AS worst_case_value,

    b.best_case_probability,
    b.worst_case_probability,
    b.probability_spread
FROM project_bands b;


-- =========================================================
-- Invoice smoothing score artifact
-- =========================================================

CREATE VIEW vw_pipeline_smoothing_score_v1 AS
WITH forecast_projects AS (
    SELECT *
    FROM vw_pipeline_forecast_project_v1
),
score_dimensions AS (
    SELECT *
    FROM (VALUES
        ('category'::TEXT),
        ('type'::TEXT),
        ('product'::TEXT),
        ('account'::TEXT)
    ) AS dimensions(dimension)
),
project_signal_tokens AS (
    SELECT
        f.project_id,
        'category'::TEXT AS dimension,
        public.smoothing_normalize_token(f.category) AS group_key,
        NULLIF(BTRIM(f.category), '') AS group_display
    FROM forecast_projects f

    UNION ALL

    SELECT
        f.project_id,
        'type'::TEXT AS dimension,
        public.smoothing_normalize_token(f.type) AS group_key,
        NULLIF(BTRIM(f.type), '') AS group_display
    FROM forecast_projects f

    UNION ALL

    SELECT
        f.project_id,
        'product'::TEXT AS dimension,
        public.smoothing_normalize_token(product_token.token) AS group_key,
        NULLIF(BTRIM(product_token.token), '') AS group_display
    FROM forecast_projects f
    CROSS JOIN LATERAL REGEXP_SPLIT_TO_TABLE(
        COALESCE(f.product_type, ''),
        '[[:space:]]*,[[:space:]]*'
    ) AS product_token(token)

    UNION ALL

    SELECT
        f.project_id,
        'account'::TEXT AS dimension,
        public.smoothing_normalize_token(account_token.token) AS group_key,
        NULLIF(BTRIM(account_token.token), '') AS group_display
    FROM forecast_projects f
    CROSS JOIN LATERAL REGEXP_SPLIT_TO_TABLE(
        COALESCE(f.account, ''),
        '[[:space:]]*,[[:space:]]*'
    ) AS account_token(token)
),
distinct_project_signal_tokens AS (
    SELECT
        pst.project_id,
        pst.dimension,
        pst.group_key,
        MIN(pst.group_display) AS group_display
    FROM project_signal_tokens pst
    WHERE pst.group_key IS NOT NULL
      AND pst.group_key <> ''
      AND pst.group_display IS NOT NULL
      AND pst.group_display <> ''
    GROUP BY pst.project_id, pst.dimension, pst.group_key
),
global_signal AS (
    SELECT
        s.as_of_date,
        s.shrunk_mature_smoothed_pct,
        s.mature_expected_spread_days,
        s.mature_project_count,
        s.confidence
    FROM public.mv_invoice_smoothing_signal_v1 s
    WHERE s.dimension = 'global'
      AND s.group_key = '__global__'
),
dimension_signal_rollups AS (
    SELECT
        f.project_id,
        d.dimension,
        g.as_of_date AS smoothing_as_of_date,
        STRING_AGG(DISTINCT t.group_key, ', ' ORDER BY t.group_key)
            FILTER (WHERE t.group_key IS NOT NULL) AS candidate_group_keys,
        STRING_AGG(DISTINCT t.group_display, ', ' ORDER BY t.group_display)
            FILTER (WHERE t.group_display IS NOT NULL) AS candidate_group_displays,
        STRING_AGG(DISTINCT s.group_key, ', ' ORDER BY s.group_key)
            FILTER (WHERE s.group_key IS NOT NULL) AS matched_group_keys,
        STRING_AGG(DISTINCT s.group_display, ', ' ORDER BY s.group_display)
            FILTER (WHERE s.group_display IS NOT NULL) AS matched_group_displays,
        COUNT(t.group_key) AS candidate_token_count,
        COUNT(s.group_key) AS matched_signal_count,
        (COUNT(t.group_key) = 0 OR COUNT(s.group_key) < COUNT(t.group_key)) AS signal_fallback_used,
        ROUND(
            AVG(COALESCE(s.shrunk_mature_smoothed_pct, g.shrunk_mature_smoothed_pct)),
            6
        )::NUMERIC(8,6) AS signal_rate,
        ROUND(
            AVG(COALESCE(s.mature_expected_spread_days, g.mature_expected_spread_days)),
            2
        )::NUMERIC(10,2) AS signal_spread_days,
        COALESCE(
            SUM(COALESCE(s.mature_project_count, g.mature_project_count)),
            0
        )::BIGINT AS mature_project_count
    FROM forecast_projects f
    CROSS JOIN score_dimensions d
    CROSS JOIN global_signal g
    LEFT JOIN distinct_project_signal_tokens t
        ON t.project_id = f.project_id
       AND t.dimension = d.dimension
    LEFT JOIN public.mv_invoice_smoothing_signal_v1 s
        ON s.as_of_date = g.as_of_date
       AND s.dimension = d.dimension
       AND s.group_key = t.group_key
    GROUP BY
        f.project_id,
        d.dimension,
        g.as_of_date
),
pivoted_signals AS (
    SELECT
        dsr.project_id,
        MAX(dsr.smoothing_as_of_date) AS smoothing_as_of_date,

        MAX(dsr.candidate_group_keys) FILTER (WHERE dsr.dimension = 'category') AS category_signal_group_key,
        MAX(dsr.candidate_group_displays) FILTER (WHERE dsr.dimension = 'category') AS category_signal_group_display,
        MAX(dsr.signal_rate) FILTER (WHERE dsr.dimension = 'category') AS category_rate,
        MAX(dsr.signal_spread_days) FILTER (WHERE dsr.dimension = 'category') AS category_spread_days,
        MAX(dsr.mature_project_count) FILTER (WHERE dsr.dimension = 'category') AS category_mature_project_count,
        MAX(dsr.candidate_token_count) FILTER (WHERE dsr.dimension = 'category') AS category_candidate_token_count,
        MAX(dsr.matched_signal_count) FILTER (WHERE dsr.dimension = 'category') AS category_matched_signal_count,
        BOOL_OR(dsr.signal_fallback_used) FILTER (WHERE dsr.dimension = 'category') AS category_signal_fallback_used,

        MAX(dsr.candidate_group_keys) FILTER (WHERE dsr.dimension = 'type') AS type_signal_group_key,
        MAX(dsr.candidate_group_displays) FILTER (WHERE dsr.dimension = 'type') AS type_signal_group_display,
        MAX(dsr.signal_rate) FILTER (WHERE dsr.dimension = 'type') AS type_rate,
        MAX(dsr.signal_spread_days) FILTER (WHERE dsr.dimension = 'type') AS type_spread_days,
        MAX(dsr.mature_project_count) FILTER (WHERE dsr.dimension = 'type') AS type_mature_project_count,
        MAX(dsr.candidate_token_count) FILTER (WHERE dsr.dimension = 'type') AS type_candidate_token_count,
        MAX(dsr.matched_signal_count) FILTER (WHERE dsr.dimension = 'type') AS type_matched_signal_count,
        BOOL_OR(dsr.signal_fallback_used) FILTER (WHERE dsr.dimension = 'type') AS type_signal_fallback_used,

        MAX(dsr.candidate_group_keys) FILTER (WHERE dsr.dimension = 'product') AS product_signal_group_key,
        MAX(dsr.candidate_group_displays) FILTER (WHERE dsr.dimension = 'product') AS product_signal_group_display,
        MAX(dsr.signal_rate) FILTER (WHERE dsr.dimension = 'product') AS product_rate,
        MAX(dsr.signal_spread_days) FILTER (WHERE dsr.dimension = 'product') AS product_spread_days,
        MAX(dsr.mature_project_count) FILTER (WHERE dsr.dimension = 'product') AS product_mature_project_count,
        MAX(dsr.candidate_token_count) FILTER (WHERE dsr.dimension = 'product') AS product_candidate_token_count,
        MAX(dsr.matched_signal_count) FILTER (WHERE dsr.dimension = 'product') AS product_matched_signal_count,
        BOOL_OR(dsr.signal_fallback_used) FILTER (WHERE dsr.dimension = 'product') AS product_signal_fallback_used,

        MAX(dsr.candidate_group_keys) FILTER (WHERE dsr.dimension = 'account') AS account_signal_group_key,
        MAX(dsr.candidate_group_displays) FILTER (WHERE dsr.dimension = 'account') AS account_signal_group_display,
        MAX(dsr.signal_rate) FILTER (WHERE dsr.dimension = 'account') AS account_rate,
        MAX(dsr.signal_spread_days) FILTER (WHERE dsr.dimension = 'account') AS account_spread_days,
        MAX(dsr.mature_project_count) FILTER (WHERE dsr.dimension = 'account') AS account_mature_project_count,
        MAX(dsr.candidate_token_count) FILTER (WHERE dsr.dimension = 'account') AS account_candidate_token_count,
        MAX(dsr.matched_signal_count) FILTER (WHERE dsr.dimension = 'account') AS account_matched_signal_count,
        BOOL_OR(dsr.signal_fallback_used) FILTER (WHERE dsr.dimension = 'account') AS account_signal_fallback_used
    FROM dimension_signal_rollups dsr
    GROUP BY dsr.project_id
),
weighted_scores AS (
    SELECT
        f.*,
        ps.smoothing_as_of_date,

        ps.category_signal_group_key,
        ps.category_signal_group_display,
        ps.category_rate,
        ps.category_spread_days,
        ps.category_mature_project_count,
        CASE
            WHEN ps.category_mature_project_count >= 50 THEN 'High'
            WHEN ps.category_mature_project_count >= 15 THEN 'Medium'
            WHEN ps.category_mature_project_count >= 5 THEN 'Low'
            ELSE 'Very low'
        END AS category_confidence,
        ps.category_candidate_token_count,
        ps.category_matched_signal_count,
        ps.category_signal_fallback_used,

        ps.type_signal_group_key,
        ps.type_signal_group_display,
        ps.type_rate,
        ps.type_spread_days,
        ps.type_mature_project_count,
        CASE
            WHEN ps.type_mature_project_count >= 50 THEN 'High'
            WHEN ps.type_mature_project_count >= 15 THEN 'Medium'
            WHEN ps.type_mature_project_count >= 5 THEN 'Low'
            ELSE 'Very low'
        END AS type_confidence,
        ps.type_candidate_token_count,
        ps.type_matched_signal_count,
        ps.type_signal_fallback_used,

        ps.product_signal_group_key,
        ps.product_signal_group_display,
        ps.product_rate,
        ps.product_spread_days,
        ps.product_mature_project_count,
        CASE
            WHEN ps.product_mature_project_count >= 50 THEN 'High'
            WHEN ps.product_mature_project_count >= 15 THEN 'Medium'
            WHEN ps.product_mature_project_count >= 5 THEN 'Low'
            ELSE 'Very low'
        END AS product_confidence,
        ps.product_candidate_token_count,
        ps.product_matched_signal_count,
        ps.product_signal_fallback_used,

        ps.account_signal_group_key,
        ps.account_signal_group_display,
        ps.account_rate,
        ps.account_spread_days,
        ps.account_mature_project_count,
        CASE
            WHEN ps.account_mature_project_count >= 50 THEN 'High'
            WHEN ps.account_mature_project_count >= 15 THEN 'Medium'
            WHEN ps.account_mature_project_count >= 5 THEN 'Low'
            ELSE 'Very low'
        END AS account_confidence,
        ps.account_candidate_token_count,
        ps.account_matched_signal_count,
        ps.account_signal_fallback_used,

        ROUND(
            (
                ps.category_rate * 0.30::NUMERIC +
                ps.type_rate * 0.10::NUMERIC +
                ps.product_rate * 0.30::NUMERIC +
                ps.account_rate * 0.30::NUMERIC
            ),
            6
        )::NUMERIC(8,6) AS combined_smoothed_probability,
        ROUND(
            (
                ps.category_spread_days * 0.30::NUMERIC +
                ps.type_spread_days * 0.10::NUMERIC +
                ps.product_spread_days * 0.30::NUMERIC +
                ps.account_spread_days * 0.30::NUMERIC
            ),
            2
        )::NUMERIC(10,2) AS expected_spread_days
    FROM forecast_projects f
    INNER JOIN pivoted_signals ps
        ON ps.project_id = f.project_id
),
banded_scores AS (
    SELECT
        ws.*,
        CASE
            WHEN ws.combined_smoothed_probability >= 0.55::NUMERIC THEN 'Very High'
            WHEN ws.combined_smoothed_probability >= 0.45::NUMERIC THEN 'High'
            WHEN ws.combined_smoothed_probability >= 0.35::NUMERIC THEN 'Moderate'
            ELSE 'Low'
        END AS risk_band
    FROM weighted_scores ws
)
SELECT
    bs.project_uuid,
    bs.project_id,
    bs.item_name,
    bs.project_name,
    bs.account,
    bs.type,
    bs.category,
    bs.product_type,
    bs.product_key,
    bs.pipeline_stage,
    bs.stage_bucket,
    bs.contract_value,
    bs.total_order_value,
    bs.new_enquiry_value,
    bs.date_created,
    bs.probability AS conversion_probability,
    bs.forecast_date,
    bs.forecast_month,
    bs.forecast_date_source,
    bs.analysis_timestamp,
    bs.expected_gestation_days,
    bs.expected_conversion_rate,
    bs.conversion_confidence,
    bs.rating_score,
    bs.probability_percent,
    bs.committed_value,
    bs.expected_value,
    bs.best_case_value,
    bs.worst_case_value,
    bs.best_case_probability,
    bs.worst_case_probability,
    bs.probability_spread,

    bs.smoothing_as_of_date,

    bs.category_signal_group_key,
    bs.category_signal_group_display,
    bs.category_rate,
    bs.category_spread_days,
    bs.category_mature_project_count,
    bs.category_confidence,
    bs.category_candidate_token_count,
    bs.category_matched_signal_count,
    bs.category_signal_fallback_used,

    bs.type_signal_group_key,
    bs.type_signal_group_display,
    bs.type_rate,
    bs.type_spread_days,
    bs.type_mature_project_count,
    bs.type_confidence,
    bs.type_candidate_token_count,
    bs.type_matched_signal_count,
    bs.type_signal_fallback_used,

    bs.product_signal_group_key,
    bs.product_signal_group_display,
    bs.product_rate,
    bs.product_spread_days,
    bs.product_mature_project_count,
    bs.product_confidence,
    bs.product_candidate_token_count,
    bs.product_matched_signal_count,
    bs.product_signal_fallback_used,

    bs.account_signal_group_key,
    bs.account_signal_group_display,
    bs.account_rate,
    bs.account_spread_days,
    bs.account_mature_project_count,
    bs.account_confidence,
    bs.account_candidate_token_count,
    bs.account_matched_signal_count,
    bs.account_signal_fallback_used,

    bs.combined_smoothed_probability,
    bs.expected_spread_days,
    bs.risk_band,
    CASE bs.risk_band
        WHEN 'Very High' THEN 'Adopt smoothing by default'
        WHEN 'High' THEN 'Model smoothing scenario'
        WHEN 'Moderate' THEN 'Commercial review / light smoothing'
        ELSE 'No default smoothing'
    END AS workbook_suggested_treatment,
    (
        bs.risk_band = 'Very High'
        OR (
            bs.expected_spread_days >= 120::NUMERIC
            AND bs.risk_band IN ('High', 'Moderate')
        )
    ) AS default_smoothing_recommended,
    CASE
        WHEN bs.risk_band = 'Very High' THEN 'Default smoothing recommended'
        WHEN bs.expected_spread_days >= 120::NUMERIC
             AND bs.risk_band IN ('High', 'Moderate')
            THEN 'Escalate to default smoothing due to long expected spread'
        WHEN bs.expected_spread_days >= 120::NUMERIC
            THEN 'Review long expected spread before assuming unsmoothed timing'
        WHEN bs.risk_band = 'High' THEN 'Model smoothing scenario'
        WHEN bs.risk_band = 'Moderate' THEN 'Commercial review / light smoothing'
        ELSE 'No default smoothing'
    END AS adoption_recommendation,
    ROUND((bs.expected_value * bs.combined_smoothed_probability)::NUMERIC, 2)::NUMERIC(12,2)
        AS smoothed_expected_value,
    ROUND((bs.expected_value * (1::NUMERIC - bs.combined_smoothed_probability))::NUMERIC, 2)::NUMERIC(12,2)
        AS unsmoothed_expected_value
FROM banded_scores bs;

COMMENT ON VIEW vw_pipeline_smoothing_score_v1 IS
    'Phase 3 project-level invoice smoothing adoption scores using workbook 30/10/30/30 weighting and global signal fallback.';


-- =========================================================
-- Stage 5: Smoothed monthly revenue allocation
-- =========================================================

CREATE MATERIALIZED VIEW mv_pipeline_smoothed_revenue_monthly_12m_v1 AS
WITH bounds AS (
    SELECT
        DATE_TRUNC('month', CURRENT_DATE)::DATE AS window_start,
        (DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '12 months')::DATE AS window_end
),
scored_projects AS (
    SELECT
        s.project_id,
        s.stage_bucket,
        s.forecast_date::DATE AS forecast_date,
        s.forecast_month,
        COALESCE(s.expected_value, 0::NUMERIC)::NUMERIC AS expected_value,
        GREATEST(
            0::NUMERIC,
            LEAST(1::NUMERIC, COALESCE(s.combined_smoothed_probability, 0::NUMERIC))
        ) AS smoothing_probability,
        GREATEST(0::NUMERIC, COALESCE(s.expected_spread_days, 0::NUMERIC)) AS expected_spread_days
    FROM vw_pipeline_smoothing_score_v1 s
    CROSS JOIN bounds b
    WHERE s.forecast_month >= b.window_start
      AND s.forecast_month < b.window_end
),
project_values AS (
    SELECT
        sp.*,
        (sp.expected_value * sp.smoothing_probability) AS smoothed_value,
        (sp.expected_value * (1::NUMERIC - sp.smoothing_probability)) AS unsmoothed_value,
        GREATEST(CEIL(sp.expected_spread_days)::INTEGER, 1) AS spread_day_count
    FROM scored_projects sp
),
allocation_periods AS (
    SELECT
        pv.*,
        b.window_start,
        b.window_end,
        LEAST((pv.forecast_date + pv.spread_day_count)::DATE, b.window_end) AS allocation_end_date
    FROM project_values pv
    CROSS JOIN bounds b
),
allocation_periods_with_days AS (
    SELECT
        ap.*,
        GREATEST(
            EXTRACT(EPOCH FROM (ap.allocation_end_date::TIMESTAMP - ap.forecast_date::TIMESTAMP))
                / 86400::NUMERIC,
            1::NUMERIC
        ) AS allocation_day_count
    FROM allocation_periods ap
),
unsmoothed_allocations AS (
    SELECT
        ap.project_id,
        ap.stage_bucket,
        ap.forecast_month,
        ap.unsmoothed_value AS unsmoothed_allocated_value,
        0::NUMERIC AS smoothed_allocated_value
    FROM allocation_periods_with_days ap
),
smoothed_allocations AS (
    SELECT
        ap.project_id,
        ap.stage_bucket,
        allocation_month.month_start::DATE AS forecast_month,
        0::NUMERIC AS unsmoothed_allocated_value,
        (
            ap.smoothed_value *
            GREATEST(
                EXTRACT(EPOCH FROM (
                    LEAST(
                        ap.allocation_end_date::TIMESTAMP,
                        (allocation_month.month_start + INTERVAL '1 month')::TIMESTAMP
                    ) - GREATEST(
                        ap.forecast_date::TIMESTAMP,
                        allocation_month.month_start::TIMESTAMP
                    )
                )) / 86400::NUMERIC,
                0::NUMERIC
            ) / ap.allocation_day_count
        ) AS smoothed_allocated_value
    FROM allocation_periods_with_days ap
    CROSS JOIN LATERAL GENERATE_SERIES(
        DATE_TRUNC('month', ap.forecast_date)::DATE,
        DATE_TRUNC('month', (ap.allocation_end_date - INTERVAL '1 day')::DATE)::DATE,
        INTERVAL '1 month'
    ) AS allocation_month(month_start)
),
allocation_rows AS (
    SELECT *
    FROM unsmoothed_allocations

    UNION ALL

    SELECT *
    FROM smoothed_allocations
)
SELECT
    ar.forecast_month,
    ar.stage_bucket,
    COUNT(DISTINCT ar.project_id) AS project_count,
    COUNT(DISTINCT ar.project_id) FILTER (
        WHERE ar.unsmoothed_allocated_value <> 0
    ) AS unsmoothed_project_count,
    COUNT(DISTINCT ar.project_id) FILTER (
        WHERE ar.smoothed_allocated_value <> 0
    ) AS smoothed_project_count,
    ROUND(SUM(ar.unsmoothed_allocated_value), 2)::NUMERIC(14,2) AS unsmoothed_expected_value,
    ROUND(SUM(ar.smoothed_allocated_value), 2)::NUMERIC(14,2) AS smoothed_expected_value,
    ROUND(
        SUM(ar.unsmoothed_allocated_value + ar.smoothed_allocated_value),
        2
    )::NUMERIC(14,2) AS allocated_expected_value
FROM allocation_rows ar
CROSS JOIN bounds b
WHERE ar.forecast_month >= b.window_start
  AND ar.forecast_month < b.window_end
GROUP BY ar.forecast_month, ar.stage_bucket
ORDER BY ar.forecast_month, ar.stage_bucket;

CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_pipeline_smoothed_revenue_monthly_12m_v1_unique
    ON mv_pipeline_smoothed_revenue_monthly_12m_v1 (forecast_month, stage_bucket);

CREATE INDEX IF NOT EXISTS idx_mv_pipeline_smoothed_revenue_monthly_12m_v1_forecast_month
    ON mv_pipeline_smoothed_revenue_monthly_12m_v1 (forecast_month);

COMMENT ON MATERIALIZED VIEW mv_pipeline_smoothed_revenue_monthly_12m_v1 IS
    'Phase 4 day-weighted monthly allocation of pipeline expected value using invoice smoothing scores.';


-- =========================================================
-- Stage 2 + Stage 3: Monthly aggregate sourced from centralized project formulas
-- =========================================================

CREATE MATERIALIZED VIEW mv_pipeline_forecast_monthly_12m_v1 AS
WITH bounds AS (
    SELECT
        DATE_TRUNC('month', CURRENT_DATE)::DATE AS window_start,
        (DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '12 months')::DATE AS window_end
)
SELECT
    f.forecast_month,
    f.stage_bucket,
    COUNT(*)                                    AS project_count,
    SUM(f.contract_value)::NUMERIC(14,2)        AS contract_value,
    SUM(f.committed_value)::NUMERIC(14,2)       AS committed_value,
    SUM(f.expected_value)::NUMERIC(14,2)        AS expected_value,
    SUM(f.best_case_value)::NUMERIC(14,2)       AS best_case_value,
    SUM(f.worst_case_value)::NUMERIC(14,2)      AS worst_case_value
FROM vw_pipeline_forecast_project_v1 f
CROSS JOIN bounds b
WHERE f.forecast_month >= b.window_start
  AND f.forecast_month < b.window_end
GROUP BY f.forecast_month, f.stage_bucket
ORDER BY f.forecast_month, f.stage_bucket;

CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_pipeline_forecast_monthly_12m_v1_unique
    ON mv_pipeline_forecast_monthly_12m_v1 (forecast_month, stage_bucket);

CREATE INDEX IF NOT EXISTS idx_mv_pipeline_forecast_monthly_12m_v1_forecast_month
    ON mv_pipeline_forecast_monthly_12m_v1 (forecast_month);
    

-- ============================================================
-- Enquiry Value Forecast Views (Power BI built-in forecasting)
-- ============================================================

CREATE OR REPLACE VIEW vw_actual_enquiry_monthly_v1 AS
WITH latest_analysis AS (
    SELECT
        ar.project_id,
        ar.expected_conversion_rate,
        ROW_NUMBER() OVER (
            PARTITION BY ar.project_id
            ORDER BY ar.analysis_timestamp DESC NULLS LAST, ar.id DESC
        ) AS rn
    FROM analysis_results ar
),
enquiry_actuals AS (
    SELECT
        DATE_TRUNC('month', p.date_created)::DATE AS enquiry_month,
        COUNT(*) AS project_count,
        SUM(p.new_enquiry_value)::NUMERIC(14,2) AS actual_enquiry_value,
        SUM(
            p.new_enquiry_value *
            GREATEST(0::NUMERIC, LEAST(1::NUMERIC, COALESCE(la.expected_conversion_rate, 0::NUMERIC)))
        )::NUMERIC(14,2) AS actual_pipeline_value
    FROM projects p
    LEFT JOIN latest_analysis la
        ON la.project_id = p.monday_id
       AND la.rn = 1
    WHERE p.date_created IS NOT NULL
      AND COALESCE(p.new_enquiry_value, 0) > 0
    GROUP BY 1
),
bounds AS (
    SELECT
        COALESCE(
            (SELECT MIN(enquiry_month) FROM enquiry_actuals),
            DATE_TRUNC('month', CURRENT_DATE)::DATE
        ) AS min_month,
        (DATE_TRUNC('month', CURRENT_DATE) - INTERVAL '1 month')::DATE AS max_month
),
months AS (
    SELECT
        GENERATE_SERIES(
            DATE_TRUNC('month', (SELECT min_month FROM bounds))::DATE,
            (SELECT max_month FROM bounds),
            INTERVAL '1 month'
        )::DATE AS month_start
)
SELECT
    m.month_start AS enquiry_month,
    COALESCE(a.project_count, 0)::INTEGER AS project_count,
    COALESCE(a.actual_enquiry_value, 0)::NUMERIC(14,2) AS actual_enquiry_value,
    COALESCE(a.actual_pipeline_value, 0)::NUMERIC(14,2) AS actual_pipeline_value
FROM months m
LEFT JOIN enquiry_actuals a
    ON a.enquiry_month = m.month_start
ORDER BY m.month_start;


CREATE OR REPLACE VIEW vw_enquiry_value_forecast_chart_v1 AS
SELECT
    enquiry_month AS month_start,
    actual_pipeline_value AS actual_enquiry_value,
    actual_enquiry_value AS gross_enquiry_value
FROM vw_actual_enquiry_monthly_v1
ORDER BY month_start;

-- ============================================================
-- Bookings(Contracted Value) Chart Views
-- ============================================================

-- Actual Bookings Monthly View: Uses total_order_value and date_order_received from the projects table

CREATE OR REPLACE VIEW vw_actual_bookings_monthly_v1 AS
WITH booking_actuals AS (
    SELECT
        DATE_TRUNC('month', p.date_order_received)::DATE AS booking_month,
        COUNT(*) AS project_count,
        SUM(p.total_order_value)::NUMERIC(14,2) AS actual_bookings
    FROM projects p
    WHERE p.date_order_received IS NOT NULL
      AND COALESCE(p.total_order_value, 0) > 0
      AND p.pipeline_stage IN (
          'Won - Open (Order Received)',
          'Won - Closed (Invoiced)',
          'Won Via Other Ref'
      )
    GROUP BY 1
),
bounds AS (
    SELECT
        COALESCE(
            (SELECT MIN(booking_month) FROM booking_actuals),
            DATE_TRUNC('month', CURRENT_DATE)::DATE
        ) AS min_month,
        (DATE_TRUNC('month', CURRENT_DATE) - INTERVAL '1 month')::DATE AS max_month
),
months AS (
    SELECT
        GENERATE_SERIES(
            DATE_TRUNC('month', (SELECT min_month FROM bounds))::DATE,
            (SELECT max_month FROM bounds),
            INTERVAL '1 month'
        )::DATE AS month_start
)
SELECT
    m.month_start AS booking_month,
    COALESCE(a.project_count, 0)::BIGINT AS project_count,
    COALESCE(a.actual_bookings, 0)::NUMERIC(14,2) AS actual_bookings
FROM months m
LEFT JOIN booking_actuals a
    ON a.booking_month = m.month_start
ORDER BY m.month_start;


CREATE OR REPLACE VIEW vw_bookings_forecast_chart_v1 AS
SELECT
    booking_month AS month_start,
    actual_bookings
FROM vw_actual_bookings_monthly_v1
ORDER BY month_start;

-- ==========================================================
-- Revenue Forecast Views
-- ==========================================================

-- Actual Revenue Monthly View: Uses invoice_date and amount_invoiced from the subitems table
CREATE OR REPLACE VIEW vw_actual_revenue_monthly_v1 AS
WITH revenue_actuals AS (
    SELECT
        DATE_TRUNC('month', s.invoice_date)::DATE AS revenue_month,
        COUNT(DISTINCT s.parent_monday_id) AS project_count,
        COUNT(*) AS invoice_count,
        SUM(s.amount_invoiced)::NUMERIC(14,2) AS actual_revenue
    FROM subitems s
    INNER JOIN projects p
        ON p.monday_id = s.parent_monday_id
    WHERE s.invoice_date IS NOT NULL
      AND COALESCE(s.amount_invoiced, 0) > 0
      AND p.pipeline_stage = 'Won - Closed (Invoiced)'
    GROUP BY 1
),
bounds AS (
    SELECT
        COALESCE(
            (SELECT MIN(revenue_month) FROM revenue_actuals),
            DATE_TRUNC('month', CURRENT_DATE)::DATE
        ) AS min_month,
        (DATE_TRUNC('month', CURRENT_DATE) - INTERVAL '1 month')::DATE AS max_month
),
months AS (
    SELECT
        GENERATE_SERIES(
            DATE_TRUNC('month', (SELECT min_month FROM bounds))::DATE,
            (SELECT max_month FROM bounds),
            INTERVAL '1 month'
        )::DATE AS month_start
)
SELECT
    m.month_start AS revenue_month,
    COALESCE(a.project_count, 0)::BIGINT AS project_count,
    COALESCE(a.invoice_count, 0)::BIGINT AS invoice_count,
    COALESCE(a.actual_revenue, 0)::NUMERIC(14,2) AS actual_revenue
FROM months m
LEFT JOIN revenue_actuals a
    ON a.revenue_month = m.month_start
ORDER BY m.month_start;


CREATE OR REPLACE VIEW vw_revenue_forecast_chart_v1 AS
SELECT
    revenue_month AS month_start,
    actual_revenue
FROM vw_actual_revenue_monthly_v1
ORDER BY month_start;

-- ===========================================================================================================================================
-- Monthly Weighted Enquiry Value View: Uses new_enquiry_value and expected_conversion_rate from the projects table and analysis_results table
-- ===========================================================================================================================================

CREATE OR REPLACE VIEW vw_weighted_enquiry_value_monthly_v1 AS
WITH latest_analysis AS (
    SELECT
        ar.project_id,
        ar.expected_conversion_rate,
        ROW_NUMBER() OVER (
            PARTITION BY ar.project_id
            ORDER BY ar.analysis_timestamp DESC NULLS LAST, ar.id DESC
        ) AS rn
    FROM analysis_results ar
)
SELECT
    DATE_TRUNC('month', p.date_created)::DATE AS enquiry_month,
    COUNT(*)::INTEGER AS enquiry_count_all,
    SUM(CASE WHEN COALESCE(p.new_enquiry_value, 0) > 0 THEN 1 ELSE 0 END)::INTEGER AS enquiry_count_valued,
    SUM(
        GREATEST(COALESCE(p.new_enquiry_value, 0), 0)
        * GREATEST(0::NUMERIC, LEAST(1::NUMERIC, COALESCE(la.expected_conversion_rate, 0::NUMERIC)))
    )::FLOAT8 AS weighted_enquiry_value
FROM projects p
LEFT JOIN latest_analysis la
    ON la.project_id = p.monday_id
   AND la.rn = 1
WHERE p.date_created IS NOT NULL
  AND p.date_created >= DATE '2022-01-01'
  AND DATE_TRUNC('month', p.date_created)::DATE < DATE_TRUNC('month', CURRENT_DATE)::DATE
GROUP BY 1
ORDER BY 1;